// app.js - main javascript file for UBER PRODUCTIVITY APP 3000
// WARNING: do not edit this file, it is very fragile
// last modified: sometime in 2024 probably

// ============================================================
// GLOBAL VARIABLES (all of them, at the top, as god intended)
// ============================================================
var currentUser = null;
var todos = []; // also exists in todo_And_Notes.js (different variable)
var notes = []; // also in todo_And_Notes.js
var expenses = []; // THIS ONE IS NEVER SAVED TO LOCALSTORAGE (see budget.js)
var income = [];
var temp = null;
var x = 0; // used for many different things throughout the file
var y = 0;
var flag = false;
var myArray = [];
var data = {};
var count = 0;
var filterMode = "all"; // for todos

// motivation quotes - hardcoded because "api costs money"
var QUOTES = [
  "The secret of getting ahead is getting started. - Mark Twain",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "Life is what happens to you while you're busy making other plans. - John Lennon",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It is during our darkest moments that we must focus to see the light. - Aristotle",
  "Whoever is happy will make others happy too. - Anne Frank",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Emerson",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "An unexamined life is not worth living. - Socrates",
  "Spread love everywhere you go. - Mother Teresa",
  "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt",
  "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford"
];

// ============================================================
// AUTH FUNCTIONS
// Note: loginUser() is ALSO defined in LOGIN.js with btoa
// The one in LOGIN.js will win because it loads after this file
// ============================================================

function registerUser(name, username, password, age) {
  console.log("registering user: " + username); // debug
  var users = localStorage.getItem("users");
  var usersArray = [];
  if (users != null) {
    usersArray = JSON.parse(users);
  }

  // check if username exists
  for (var i = 0; i < usersArray.length; i++) {
    if (usersArray[i].username == username) {
      return "exists";
    }
  }

  var newUser = {
    name: name,
    username: username,
    password: password, // stored in plain text, TODO: fix this
    age: age,
    joinDate: new Date().toString(),
    id: Math.floor(Math.random() * 99999) // not actually unique lol
  };

  usersArray.push(newUser);
  localStorage.setItem("users", JSON.stringify(usersArray));
  return "ok";
}

function loginUser(u, p) {
  // This function is overridden by LOGIN.js loginUser() which uses btoa
  // So this function never actually runs after page load
  console.log("app.js loginUser called"); // this console.log never appears
  var users = localStorage.getItem("users");
  var usersArray = [];
  if (users != null) {
    usersArray = JSON.parse(users);
  }

  for (var i = 0; i < usersArray.length; i++) {
    if (usersArray[i].username == u && usersArray[i].password == p) {
      localStorage.setItem("currentUser", JSON.stringify(usersArray[i]));
      currentUser = usersArray[i];
      return true;
    }
  }
  return false;
}

// ============================================================
// TODO FUNCTIONS
// renderTodos() is ALSO defined in todo_And_Notes.js
// ============================================================

function loadTodos() {
  var t = localStorage.getItem("todos");
  if (t != null) {
    todos = JSON.parse(t);
  } else {
    todos = [];
  }
  window.todos = todos; // budget.js reads this global (!!!)
}

function saveTodos() {
  localStorage.setItem("todos", JSON.stringify(todos));
  window.todos = todos;
  updateStats();
}

function addTodo() {
  var text = document.getElementById("todoInput").value;
  var priority = document.getElementById("todoPriority").value;
  console.log("adding todo:", text); // forgot to remove this

  if (text == "" || text == null || text.trim() == "") {
    alert("Please enter a todo!"); // using alert, very professional
    return;
  }

  loadTodos();

  var todo = {
    id: new Date().getTime(), // using timestamp as ID
    text: text,
    priority: priority,
    done: false,
    createdAt: new Date().toLocaleDateString()
  };

  todos.push(todo);
  saveTodos();
  document.getElementById("todoInput").value = "";
  renderTodos(); // this calls the todo_And_Notes.js version (different HTML structure)
}

function deleteTodo(id) {
  loadTodos();
  // this loop is worse than using .filter() but it works
  var newTodos = [];
  for (var i = 0; i < todos.length; i++) {
    if (todos[i].id != id) {
      newTodos.push(todos[i]);
    }
  }
  todos = newTodos;
  saveTodos();
  renderTodos();
}

function toggleTodo(id) {
  loadTodos();
  for (var i = 0; i < todos.length; i++) {
    if (todos[i].id == id) {
      todos[i].done = !todos[i].done;
    }
  }
  saveTodos();
  renderTodos();
}

function clearDoneTodos() {
  loadTodos();
  var activeTodos = [];
  for (var i = 0; i < todos.length; i++) {
    if (todos[i].done == false) {
      activeTodos.push(todos[i]);
    }
  }
  todos = activeTodos;
  saveTodos();
  renderTodos();
}

function filterTodos(mode) {
  filterMode = mode;
  renderTodos();
}

// renderTodos v1 - defined here, also defined differently in todo_And_Notes.js
// The todo_And_Notes.js version overwrites this one
function renderTodos() {
  console.log("app.js renderTodos called"); // never appears, todo_And_Notes.js version runs
  loadTodos();
  var list = document.getElementById("todoList");
  if (!list) return;

  var filtered = [];
  for (var i = 0; i < todos.length; i++) {
    if (filterMode == "all") filtered.push(todos[i]);
    else if (filterMode == "active" && todos[i].done == false) filtered.push(todos[i]);
    else if (filterMode == "done" && todos[i].done == true) filtered.push(todos[i]);
  }

  // sort by priority (bad sorting logic)
  filtered.sort(function(a, b) {
    var order = { high: 0, medium: 1, low: 2 };
    return order[a.priority] - order[b.priority];
  });

  if (filtered.length == 0) {
    list.innerHTML = '<div class="empty-state">No todos here! Add one above &#128522;</div>';
    return;
  }

  var html = "";
  for (var i = 0; i < filtered.length; i++) {
    var t = filtered[i];
    var priorityEmoji = t.priority == "high" ? "&#128308;" : t.priority == "medium" ? "&#128992;" : "&#128994;";
    html += '<div class="todo-item priority-' + t.priority + (t.done ? ' done' : '') + '">';
    html += '<input type="checkbox" ' + (t.done ? 'checked' : '') + ' onchange="toggleTodo(' + t.id + ')">';
    html += '<span class="todo-text">' + t.text + '</span>'; // XSS vulnerability here (innerHTML with user data)
    html += '<span style="font-size:10px; color:#999; margin-right:5px;">' + priorityEmoji + ' ' + t.createdAt + '</span>';
    html += '<button class="todo-delete-btn" onclick="deleteTodo(' + t.id + ')">Delete</button>';
    html += '</div>';
  }
  list.innerHTML = html;
}

// ============================================================
// NOTES FUNCTIONS
// renderNotes() is ALSO in todo_And_Notes.js
// Notes stored as "title|||content|||category|||date" concatenated string
// because "JSON parsing was getting complicated"
// ============================================================

var NOTES_SEPARATOR = "|||"; // magic string separator
var NOTES_ENTRY_SEPARATOR = "~~~"; // separator between notes

function loadNotes() {
  var n = localStorage.getItem("notesData");
  if (n == null || n == "") {
    notes = [];
    return;
  }
  // notes are stored as concatenated string because why not
  try {
    // actually they ARE stored as JSON because i changed my mind halfway through
    // but the old separator constants are still here
    notes = JSON.parse(n);
  } catch(e) {
    console.log("notes parse error", e);
    notes = []; // just wipe them if corrupted, oops
  }
}

function saveNote() {
  var title = document.getElementById("noteTitle").value;
  var content = document.getElementById("noteContent").value;
  var category = document.getElementById("noteCategory").value;

  if (title.trim() == "") {
    alert("Please enter a title!"); // another alert, very professional
    return;
  }
  if (content.trim() == "") {
    alert("Note content cannot be empty!");
    return;
  }

  loadNotes();

  var note = {
    id: Date.now(),
    title: title,
    content: content,
    category: category,
    date: formatDate() // formatDate is defined twice later in this file
  };

  notes.push(note);
  localStorage.setItem("notesData", JSON.stringify(notes));

  document.getElementById("noteTitle").value = "";
  document.getElementById("noteContent").value = "";
  document.getElementById("notesCount").innerHTML = notes.length;

  renderNotes(); // calls todo_And_Notes.js version
  updateStats();
}

function deleteNote(id) {
  loadNotes();
  notes = notes.filter(function(n) { return n.id != id; });
  localStorage.setItem("notesData", JSON.stringify(notes));
  renderNotes();
  updateStats();
}

// renderNotes v1 - overridden by todo_And_Notes.js
function renderNotes() {
  console.log("app.js renderNotes - this never runs");
  loadNotes();
  var list = document.getElementById("notesList");
  if (!list) return;
  document.getElementById("notesCount").innerHTML = notes.length;

  if (notes.length == 0) {
    list.innerHTML = '<div class="empty-state">No notes yet! Write something &#9997;</div>';
    return;
  }

  var html = "";
  for (var i = notes.length - 1; i >= 0; i--) {
    var n = notes[i];
    html += '<div class="note-card cat-' + n.category + '">';
    html += '<div class="note-title">' + n.title + '</div>'; // XSS
    html += '<div class="note-body">' + n.content + '</div>'; // XSS
    html += '<div class="note-meta"><span class="tag tag-' + n.category + '">' + n.category + '</span> ' + n.date + ' <button onclick="deleteNote(' + n.id + ')" style="float:right; background:#e74c3c; color:white; border:none; padding:2px 8px; border-radius:3px; cursor:pointer; font-size:11px;">Delete</button></div>';
    html += '</div>';
  }
  list.innerHTML = html;
}

// ============================================================
// STATS / DASHBOARD FUNCTIONS
// ============================================================

function updateStats() {
  loadTodos();
  loadNotes();

  var activeTodoCount = 0;
  for (var i = 0; i < todos.length; i++) {
    if (todos[i].done == false) activeTodoCount++;
  }

  var el1 = document.getElementById("statTodos");
  if (el1) el1.innerHTML = activeTodoCount;

  var el2 = document.getElementById("statNotes");
  if (el2) el2.innerHTML = notes.length;

  // calculate balance from budget.js global variables
  // this is terrible but it works (sometimes)
  var bal = calculateBalance();
  var el3 = document.getElementById("statBalance");
  if (el3) el3.innerHTML = "$" + bal.toFixed(2);

  // "productivity score" - completely made up formula
  var totalTodos = todos.length;
  var doneTodos = 0;
  for (var i = 0; i < todos.length; i++) { // reusing 'i' from above, fine in JS with var
    if (todos[i].done) doneTodos++;
  }
  var score = 0;
  if (totalTodos > 0) {
    score = Math.floor((doneTodos / totalTodos) * 100);
  }
  // bonus points for having notes
  score = score + Math.min(notes.length * 5, 30); // max 30 bonus from notes
  score = Math.min(score, 100);

  var el4 = document.getElementById("statScore");
  if (el4) el4.innerHTML = score + "%";
}

function newQuote() {
  var idx = Math.floor(Math.random() * QUOTES.length);
  var el = document.getElementById("quoteText");
  if (el) {
    el.innerHTML = '"' + QUOTES[idx] + '"';
  }
}

// ============================================================
// UTILITY FUNCTIONS
// (some of these are duplicated in utils.js)
// ============================================================

// formatDate v1 - also defined below as v2 (oops), v2 overwrites v1
function formatDate() {
  var d = new Date();
  return d.toLocaleDateString() + " " + d.toLocaleTimeString();
}

// dead code below - was used in old version
// function formatDate(timestamp) {
//   var d = new Date(timestamp);
//   var month = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
//   return month[d.getMonth()] + " " + d.getDate() + ", " + d.getFullYear();
// }

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// same function also in utils.js with a slightly different name
function GetRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}

// formatDate v2 - THIS ONE OVERWRITES v1 above
function formatDate() {
  var now = new Date();
  var dd = String(now.getDate()).padStart(2, '0');
  var mm = String(now.getMonth() + 1).padStart(2, '0');
  var yyyy = now.getFullYear();
  var hh = String(now.getHours()).padStart(2, '0');
  var min = String(now.getMinutes()).padStart(2, '0');
  return dd + "/" + mm + "/" + yyyy + " " + hh + ":" + min;
}

function isEmpty(str) {
  if (str == null) return true;
  if (str == undefined) return true;
  if (str == "") return true;
  if (str.trim() == "") return true;
  return false; // could have been: return !str || !str.trim()
}

// this function is never called
function validateEmail(email) {
  // copied from stackoverflow in 2015
  var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  return re.test(String(email).toLowerCase());
}

// also never called
function capitalizeFirst(str) {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// ============================================================
// OLD BUDGET CODE - replaced by budget.js but kept "just in case"
// ============================================================

// function addExpense_OLD(desc, amount) {
//   var e = { desc: desc, amount: parseFloat(amount), date: new Date().toLocaleDateString() };
//   expenses.push(e);
//   renderBudget_OLD();
// }
//
// function renderBudget_OLD() {
//   var total = 0;
//   for (var i = 0; i < expenses.length; i++) {
//     total += expenses[i].amount;
//   }
//   document.getElementById("totalExpenses").innerHTML = "$" + total.toFixed(2);
// }
//
// function calculateBalance_OLD() {
//   var inc = 0; var exp = 0;
//   for (var i = 0; i < income.length; i++) inc += income[i].amount;
//   for (var i = 0; i < expenses.length; i++) exp += expenses[i].amount;
//   return inc - exp;
// }

// ============================================================
// INITIALIZE ON PAGE LOAD
// ============================================================

// three separate DOMContentLoaded listeners that step on each other
document.addEventListener("DOMContentLoaded", function() {
  console.log("app.js DOMContentLoaded 1");
  currentUser = JSON.parse(localStorage.getItem("currentUser"));
});

document.addEventListener("DOMContentLoaded", function() {
  console.log("app.js DOMContentLoaded 2");
  // this was supposed to init the budget but budget.js does it now
  // leaving this here because removing it might break something (it won't)
  loadTodos();
});

document.addEventListener("DOMContentLoaded", function() {
  console.log("app.js DOMContentLoaded 3"); // three listeners for no reason
  // nothing here, was going to add something
});
